import { Task, Column } from './types';
import { v4 as uuidv4 } from 'uuid';

export const columns: Column[] = [
  { id: 'todo', title: 'To Do', color: '#6366f1', icon: 'circle' },
  { id: 'in-progress', title: 'In Progress', color: '#f59e0b', icon: 'loader' },
  { id: 'done', title: 'Done', color: '#10b981', icon: 'check-circle' },
];

export const initialTasks: Task[] = [
  {
    id: uuidv4(),
    title: 'Design landing page',
    description: 'Create wireframes and mockups for the new landing page',
    status: 'todo',
    priority: 'high',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    dueDate: new Date(Date.now() + 86400000 * 4).toISOString(),
    tags: ['design', 'ui'],
  },
  {
    id: uuidv4(),
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment',
    status: 'todo',
    priority: 'medium',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    dueDate: new Date(Date.now() + 86400000 * 7).toISOString(),
    tags: ['devops', 'automation'],
  },
  {
    id: uuidv4(),
    title: 'Write API documentation',
    description: 'Document all REST endpoints with examples and response schemas',
    status: 'todo',
    priority: 'low',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    dueDate: new Date(Date.now() + 86400000 * 10).toISOString(),
    tags: ['docs'],
  },
  {
    id: uuidv4(),
    title: 'Implement auth flow',
    description: 'Build login, signup, and password reset functionality',
    status: 'in-progress',
    priority: 'high',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    tags: ['backend', 'security'],
  },
  {
    id: uuidv4(),
    title: 'Database optimization',
    description: 'Add indexes and optimize slow queries in the main tables',
    status: 'in-progress',
    priority: 'medium',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    dueDate: new Date(Date.now() + 86400000 * 3).toISOString(),
    tags: ['backend', 'performance'],
  },
  {
    id: uuidv4(),
    title: 'User research interviews',
    description: 'Conduct 5 user interviews to gather feedback on the new features',
    status: 'done',
    priority: 'high',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    dueDate: new Date(Date.now() - 86400000 * 1).toISOString(),
    tags: ['research', 'ux'],
  },
  {
    id: uuidv4(),
    title: 'Fix responsive layout',
    description: 'Resolve layout issues on mobile devices for the dashboard',
    status: 'done',
    priority: 'medium',
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    dueDate: new Date(Date.now() - 86400000 * 2).toISOString(),
    tags: ['frontend', 'bug'],
  },
  {
    id: uuidv4(),
    title: 'Set up monitoring',
    description: 'Configure error tracking and performance monitoring tools',
    status: 'done',
    priority: 'low',
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    dueDate: new Date(Date.now() - 86400000 * 3).toISOString(),
    tags: ['devops', 'monitoring'],
  },
];
